# -*- coding: utf-8 -*-
"""Project 107.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Lv2fVWqHdnropOLOA_02aED_LIqP44Gd
"""

from google.colab import files
data_csv=files.upload()

!pip install python-datatable
!pip install pandas
import pandas as pd
import csv
import plotly.express as px
import datatable as dt
df = pd.read_csv("Average Distance of Sports.csv", encoding="cp1252", header=None, names=["Sports","Distance(Km)"])
sports_names=[]
distance_traveled=[]
sports_names=df.groupby("Sports")
print(sports_names)
distance_traveled=df.groupby("Distance(Km)")
print(distance_traveled)
px.Bar(x="Sports",y="Distance(Km)")